# headers and icon 
title: Cassidy Metzger
info: Aspiring Physics/Astronomy PhD 
icon-pic: assets/img/headshot.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
